server:
  port: 9296
spring:
  application:
    name: CONFIG-SERVER
  profile:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Nishanth8810/config-server
          skip: true
          validation: true

